# Generated by Django 5.2.1 on 2025-05-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_options_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='combinations',
            field=models.TextField(blank=True, help_text='Список комбинаций, разделенных запятыми'),
        ),
        migrations.AddField(
            model_name='product',
            name='ratings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
